### ISSUE TITLE
UCM2 path checks

### ISSUE THREAD

**Issue by Srinivas-Kandagatla** [alsa-project/alsa-tests#4]
Hi Jaroslav,

Am bit confused with the paths that ucm-validator is checking for this card:

$cat /proc/asound/cards
 0 [LenovoYOGAC6301]: Lenovo-YOGA-C63 - Lenovo-YOGA-C630-13Q50
                      LENOVO-81JL-LenovoYOGAC630_13Q50-LNVNB161216

It seems to look for 

First path: ucm2/Lenovo-YOGA-C63/LENOVO-81JL-LenovoYOGAC630_13Q50-LNVNB161216.conf

Second path: ucm2/Lenovo-YOGA-C63/Lenovo-YOGA-C630-13Q50.conf

And finally errs out.

However pulseaudio seems to be happy with path like
ucm2/Lenovo-YOGA-C630-13Q50/Lenovo-YOGA-C630-13Q50.conf

Question is, should this also include this path as valid or is this path totally invalid?

Also Lenovo-YOGA-C630-13Q50 path seems to be much better than trimmed version of card name "Lenovo-YOGA-C63".

On @andersson setup he had to have /usr/share/alsa/ucm2/Lenovo-YOGA-C630-13Q50/Lenovo-YOGA-C630-13Q50.conf path to get pulseaudio working!
Not sure if this is to do with some particular version of PA and alsa-lib.

Wanted to send new PR for ucm but am confused with this all!
thanks,
srini

**Comment by perexg** [comment]
> However pulseaudio seems to be happy with path like
> ucm2/Lenovo-YOGA-C630-13Q50/Lenovo-YOGA-C630-13Q50.conf

It's old fallback path for ucm (not ucm2) tree. It works but I don't want to follow this way for ucm2 (thus it is not in the validator).

> Question is, should this also include this path as valid or is this path totally invalid?

It's fallback path for older configurations. PA up to 13.0 version uses it.

> Also Lenovo-YOGA-C630-13Q50 path seems to be much better than trimmed version of card name "Lenovo-YOGA-C63".

The driver name is not nice for this device (it's not the driver name but the device name), thus we end with this not so nice path (and I won't accept such configs - sorry).

When I'll find a time, I'll try to prepare a patch to put the correct driver names to the ASoC tree:

https://mailman.alsa-project.org/pipermail/alsa-devel/2020-April/166602.html

**Comment by Srinivas-Kandagatla** [comment]
Thanks for the reply,
Looks like Lenovo C360 UCM is stuck for now, One alternative option I see is to fix the model name in the dts with less then 16 chars, which is doable!
Are you okay with that approach for Lenovo C360?

DB845c does not suffer with this issue are you okay to take that ucm changes for them?

**Comment by perexg** [comment]
It seems all resolved now.
